spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@Root123
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Encryption Configuration
encryption.salt.rounds=10

jwt.algorithm.key=42ACmG7yUJXT333DtwyNGub4vXyZscvn
jwt.issuer=account
jwt.expiryInSeconds=3600

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=expertdeveloper552@gmail.com
spring.mail.password=loii dudk khdd ycxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Change Tomcat port (default is 8080)
server.port=8080

# General Configuration
app.frontend.url=http://localhost:3000

#Email logs
logging.level.org.springframework.mail=DEBUG
spring.mail.properties.mail.debug=true

# Set the logging level for different packages
logging.level.root=INFO
logging.level.com.backend.ecommerce.users=DEBUG
# Customize logging format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# application.properties
paypal.client.id=AdCiuSBs8G9TzA6vEDZr9OcrlOydfkVhrAKMiAFBUbGCuZHe0dMjsc6mTjmcnHHY1b_GSgH6K11xBV1_
paypal.client.secret=EBsd6aA-Q5qqqN-SNL4qOgLJiGO0V_3rJ9S_WD_QX86ToqPMQFwRfP1zbD8yAsWeegJouStoTAdrgKew
paypal.mode=sandbox
#paypal.success.url=http://localhost:8080/payment/success
#paypal.cancel.url=http://localhost:8080/payment/cancel

spring.thymeleaf.check-template-location=false

# AWS S3 Configuration
#cloud.aws.credentials.access-key=16aa4bba02417161e60d0d3893e1de8a
#cloud.aws.credentials.secret-key=571c7521a86f650b481422b1bdcda0c0
#cloud.aws.region.static=US-central
#cloud.aws.s3.bucket-name=ecommerce

aws.s3.accessKey=16aa4bba02417161e60d0d3893e1de8a
aws.s3.secretKey=571c7521a86f650b481422b1bdcda0c0
aws.s3.region=US-central
aws.s3.bucketName=ecommerce
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB

# TheWallet API Configuration
thewallet.api.base-url=YOUR_THEWALLET_API_BASE_URL
# e.g., https://api.thewallet.com/
thewallet.shared-secret=YOUR_SHARED_SECRET_KEY
#This is the 'secret' for MAC calculation (Page 25)
thewallet.partner-sourcereference=YOUR_PARTNER_SOURCE_REFERENCE
# Your unique identifier as a Partner

# Your Callback URL (must be publicly accessible)
thewallet.callback.url=http://localhost:8080/api/thewallet/callback

# Mobile Network Operator Channels (as per Page 28 of API doc)
thewallet.channel.tigo=TANZANIA.TIGO
thewallet.channel.vodacom=TANZANIA.VODACOM
thewallet.channel.airtel=TANZANIA.AIRTEL
thewallet.channel.halotel=TANZANIA.HALOTEL

