spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@Root123
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Encryption Configuration
encryption.salt.rounds=10

jwt.algorithm.key=42ACmG7yUJXT333DtwyNGub4vXyZscvn
jwt.issuer=account
jwt.expiryInSeconds=3600

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=expertdeveloper552@gmail.com
spring.mail.password=loii dudk khdd ycxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Change Tomcat port (default is 8080)
server.port=8080

# General Configuration
app.frontend.url=http://localhost:3000

#Email logs
logging.level.org.springframework.mail=DEBUG
spring.mail.properties.mail.debug=true

# Set the logging level for different packages
logging.level.root=INFO
logging.level.com.backend.ecommerce.users=DEBUG
# Customize logging format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Paypal Configuration
paypal.success.url=http://localhost:8080/payment/success
paypal.cancel.url=http://localhost:8080/payment/cancel
paypal.client.id=Af98hNHR6_7pWiC37NBjjUitro-G53uqg4u6IIA8S7xr6ApnbI9uSKHmy5jy-6vxYYeUSi3B6xo6dJXp
paypal.client.secret=EAUj2VxNhORNStAF4Mku2rRQv6ujGsnVe176YA1ycXEPgsd_fwEwMQMKK6oz3XxzJ2KpdTmot4KtFgso
paypal.mode=sandbox
# Use "live" for production mode

spring.thymeleaf.check-template-location=false