package com.backend.ecommerce.payments.thewallet.controller;

import com.backend.ecommerce.payments.thewallet.payload.DisbursementRequest;
import com.backend.ecommerce.payments.thewallet.payload.PushUssdRequest;
import com.backend.ecommerce.payments.thewallet.payload.TheWalletInitiateResponse;
import com.backend.ecommerce.payments.thewallet.payload.TheWalletNotification;
import com.backend.ecommerce.payments.thewallet.security.TheWalletMacGenerator;
import com.backend.ecommerce.payments.thewallet.service.TheWalletService;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/thewallet")
public class TheWalletPaymentController {

    private static final Logger log = LoggerFactory.getLogger(TheWalletPaymentController.class);

    private final TheWalletService theWalletService;
    private final TheWalletMacGenerator macGenerator; // To verify incoming notifications

    public TheWalletPaymentController(TheWalletService theWalletService, TheWalletMacGenerator macGenerator) {
        this.theWalletService = theWalletService;
        this.macGenerator = macGenerator;
    }

    /**
     * Endpoint to initiate a Push USSD (customer charge) payment.
     * Frontend would send msisdn, amount, channel, target, and an internal order ID.
     */
    @PostMapping("/initiate/push-ussd")
    public ResponseEntity<Map<String, Object>> initiatePushUssd(@RequestBody @Valid PushUssdRequest request) {
        Map<String, Object> response = new HashMap<>();
        log.info("Received Push USSD initiation request for MSISDN: {}, Reference: {}", request.getMsisdn(), request.getSourcereference());

        try {
            // Note: MAC and date are generated by the service before sending, so don't directly use request.getMac() here for validation.
            // But ensure the DTO is valid and required fields are present.
            TheWalletInitiateResponse theWalletResponse = theWalletService.initiatePushUssd(
                    request.getMsisdn(),
                    request.getAmount().toPlainString(),
                    request.getChannel(),
                    request.getTarget(),
                    request.getSourcereference()
            ).block(); // Blocking for simplicity

            if (theWalletResponse != null && theWalletResponse.getSuccess() != null && theWalletResponse.getSuccess()) {
                response.put("status", "success");
                response.put("message", "Push USSD initiated successfully.");
                response.put("theWalletReference", theWalletResponse.getReference());
                return ResponseEntity.ok(response);
            } else {
                String errorMessage = theWalletResponse != null && theWalletResponse.getError() != null ?
                        theWalletResponse.getError().getMessage() : "Unknown error from TheWallet.";
                log.error("Push USSD initiation failed for {}: {}", request.getSourcereference(), errorMessage);
                response.put("status", "failed");
                response.put("message", "Push USSD initiation failed: " + errorMessage);
                response.put("errorCode", theWalletResponse != null && theWalletResponse.getError() != null ? theWalletResponse.getError().getCode() : null);
                return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
            }
        } catch (Exception e) {
            log.error("Exception during Push USSD initiation for {}: {}", request.getSourcereference(), e.getMessage(), e);
            response.put("status", "error");
            response.put("message", "Internal server error during Push USSD initiation: " + e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(response);
        }
    }

    /**
     * Endpoint to initiate a Disbursement (payout/refund) payment.
     * Frontend would send msisdn, amount, channel, and an internal order ID.
     */
    @PostMapping("/initiate/disbursement")
    public ResponseEntity<Map<String, Object>> initiateDisbursement(@RequestBody @Valid DisbursementRequest request) {
        Map<String, Object> response = new HashMap<>();
        log.info("Received Disbursement initiation request for MSISDN: {}, Reference: {}", request.getMsisdn(), request.getSourcereference());

        try {
            TheWalletInitiateResponse theWalletResponse = theWalletService.initiateDisbursement(
                    request.getMsisdn(),
                    request.getAmount().toPlainString(),
                    request.getChannel(),
                    request.getSourcereference()
            ).block(); // Blocking for simplicity

            if (theWalletResponse != null && theWalletResponse.getSuccess() != null && theWalletResponse.getSuccess()) {
                response.put("status", "success");
                response.put("message", "Disbursement initiated successfully.");
                response.put("theWalletReference", theWalletResponse.getReference());
                return ResponseEntity.ok(response);
            } else {
                String errorMessage = theWalletResponse != null && theWalletResponse.getError() != null ?
                        theWalletResponse.getError().getMessage() : "Unknown error from TheWallet.";
                log.error("Disbursement initiation failed for {}: {}", request.getSourcereference(), errorMessage);
                response.put("status", "failed");
                response.put("message", "Disbursement initiation failed: " + errorMessage);
                response.put("errorCode", theWalletResponse != null && theWalletResponse.getError() != null ? theWalletResponse.getError().getCode() : null);
                return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
            }
        } catch (Exception e) {
            log.error("Exception during Disbursement initiation for {}: {}", request.getSourcereference(), e.getMessage(), e);
            response.put("status", "error");
            response.put("message", "Internal server error during Disbursement initiation: " + e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(response);
        }
    }

    /**
     * Endpoint to receive all types of notifications (callbacks) from TheWallet.
     * This includes Lodgement, Push USSD Notification, and Disbursement Notification.
     * The `type` field in the payload will differentiate them.
     */
    @PostMapping("/callback")
    public ResponseEntity<Map<String, Object>> handleTheWalletCallback(@RequestBody TheWalletNotification notification) {
        Map<String, Object> response = new HashMap<>();
        log.info("Received TheWallet notification: Type={}, Reference={}, MSISDN={}",
                notification.getType(), notification.getReference(), notification.getMsisdn());

        // 1. MAC Verification (Crucial for Security)
        if (!macGenerator.verifyMac(notification.getMac(), notification.getMsisdn(), notification.getDate())) {
            log.warn("Unauthorized callback: MAC verification failed for notification type {} and reference {}.",
                    notification.getType(), notification.getReference());
            response.put("success", false);
            response.put("message", "MAC verification failed. Unauthorized request.");
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        // 2. Process based on Notification Type
        switch (notification.getType().toLowerCase()) {
            case "lodgement":
                // This is a C2B payment initiated by the customer through the MNO.
                // notification.getSuccess() should always be 'true' for Lodgement (Page 11).
                log.info("Processing Lodgement Notification for MSISDN: {}, Amount: {}, OperatorRef: {}",
                        notification.getMsisdn(), notification.getAmount(), notification.getOperatorreference());
                // TODO: Update your internal order/transaction status.
                // This would typically involve finding the order by notification.getCustomerreference()
                // or notification.getSourcereference() if you provided it for a specific C2B code.
                // Example: orderService.updateOrderStatus(notification.getCustomerreference(), "PAID");
                break;
            case "ussdpush":
                // This is a confirmation for a Push USSD request you initiated.
                if (Boolean.TRUE.equals(notification.getSuccess())) {
                    log.info("Push USSD Notification SUCCESS for SourceReference: {}, TheWalletRef: {}, Amount: {}",
                            notification.getSourcereference(), notification.getReference(), notification.getAmount());
                    // TODO: Find your order/transaction by notification.getSourcereference() (your original reference)
                    // and update its status to "PAID". Store notification.getReference() (TheWallet's ref).
                    // Example: orderService.updateOrderStatus(notification.getSourcereference(), "PAID");
                } else {
                    log.warn("Push USSD Notification FAILED for SourceReference: {}, TheWalletRef: {}",
                            notification.getSourcereference(), notification.getReference());
                    // TODO: Find your order/transaction by notification.getSourcereference()
                    // and update its status to "FAILED".
                    // Example: orderService.updateOrderStatus(notification.getSourcereference(), "FAILED");
                }
                break;
            case "disbursement": // The doc calls Disbursement notifications "notification" type in sample, but also "Disbursements Notification". Using "disbursement" for clarity.
            case "notification": // As per sample payload on Page 20
                // This is a confirmation for a Disbursement request you initiated.
                if (Boolean.TRUE.equals(notification.getSuccess())) { // The sample has "success: true" on Page 20
                    log.info("Disbursement Notification SUCCESS for SourceReference: {}, TheWalletRef: {}, Amount: {}",
                            notification.getSourcereference(), notification.getReference(), notification.getAmount());
                    // TODO: Find your transaction by notification.getSourcereference()
                    // and update its status to "DISBURSED" or "COMPLETED". Store TheWallet's reference.
                    // Example: payoutService.updatePayoutStatus(notification.getSourcereference(), "COMPLETED");
                } else {
                    log.warn("Disbursement Notification FAILED for SourceReference: {}, TheWalletRef: {}",
                            notification.getSourcereference(), notification.getReference());
                    // TODO: Find your transaction by notification.getSourcereference()
                    // and update its status to "FAILED".
                    // Example: payoutService.updatePayoutStatus(notification.getSourcereference(), "FAILED");
                }
                break;
            default:
                log.warn("Received unknown notification type from TheWallet: {}", notification.getType());
                response.put("success", false);
                response.put("message", "Unknown notification type.");
                return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
        }

        // As per documentation (Page 10, Page 21), a successful response must be { "success": true }
        response.put("success", true);
        response.put("message", "Notification processed successfully.");
        return ResponseEntity.ok(response);
    }
}